# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b54fd32b321491ab3903221c6ed027f5aa524e081bda1f6632a4d0db4741f8fd89c3e161acfb1d0fa061f2a7af56843a3026d79b9bbc4f29afcecee67a486fb

test:
  secret_key_base: 955b00976827d69ea8d12d76fc19562e6a81380176f87c528676ac0d1a0e639bd93e3ddf3e8909a065e85a7ff2772a5ecba1d4a23db0c9be259928a4925dd712

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
